awsRegion: ap-southeast-1

rbac:
  create: true
  serviceAccount:
    # This value should match local.autoscaler_sa_name in locals.tf
    name: cluster-autoscaler-aws-cluster-autoscaler-chart
    annotations:
      # This value should match the ARN of the role created by module.iam_assumable_role_admin in irsa.tf
      eks.amazonaws.com/role-arn: "arn:aws:iam::494526681395:role/cluster-autoscaler"

autoDiscovery:
  clusterName: terraform-demo-eks-cluster
  enabled: true
