#!/bin/bash -eu

cd $(dirname $0)/..

TERRAFORM_IMAGE="hashicorp/terraform"
TERRAFORM_HASH="1.0.0@sha256:6dafbe34b7c18d189ff18e3dfb7cd5fc4144a2714eb2bc7b6dd9352455e8848a"
TERRAFORM_CACHE="terraform-cache"

# mkdir -p ~/.terraform.d/plugin-cache
# [ ! -f ~/.terraformrc ] && echo -e 'plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

if [ $(docker volume ls | grep ${TERRAFORM_CACHE} | wc -l) == 0 ];then
  docker volume create ${TERRAFORM_CACHE}
fi

export TF_PLUGIN_CACHE_DIR=/tmp/.terraform

docker run -it --rm --workdir /cwd \
  --volume $PWD:/cwd \
  --volume terraform-cache:/tmp/.terraform \
  --volume $HOME/.aws:/root/.aws \
  --env AWS_ACCESS_KEY_ID \
  --env AWS_SECRET_ACCESS_KEY \
  --env AWS_SESSION_TOKEN \
  --env AWS_DEFAULT_REGION \
  --env TF_PLUGIN_CACHE_DIR \
  ${TERRAFORM_IMAGE}:${TERRAFORM_HASH} "$@"
