#!/bin/bash -eu

cd $(dirname $0)/..
source ./auto/set-env-var

ACTION=$1
OBJECT=$2
ENV=${3-'test'}

CONF_DIR="./terraform/${OBJECT}"

display_status "Initialize terraform..."

# The -reconfigure option disregards any existing configuration, preventing migration of any existing state
# Use the -upgrade option if you want Terraform to ignore the dependency lock file and consider installing newer versions based on versions.tf
auto/terraform -chdir=${CONF_DIR} init -reconfigure -upgrade

# Available while using IAM user authentication rather than SSO
# if auto/terraform -chdir=${CONF_DIR} workspace new ${ENV}; then
#     display_status "Workspace '${ENV}' created!"
# fi

display_status "Start to ${ACTION} ${OBJECT} in ${ENV} via terraform..."

# auto/terraform -chdir=${CONF_DIR} workspace select ${ENV}

auto/terraform -chdir=${CONF_DIR} ${ACTION} \
-var-file env/${ENV}.tfvars

display_status "Done"
