#!/bin/bash -eu

cd $(dirname $0)/..

TERRAFORM_IMAGE="hashicorp/terraform"
TERRAFORM_HASH="0.14.3@sha256:7b1e232f564132b949b812ee138249b5398bedf3c6fab42b468d4ec8acf5343c"

mkdir -p ~/.terraform.d/plugin-cache
[ ! -f ~/.terraformrc ] && echo -e 'plugin_cache_dir   = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

docker run -it --workdir /cwd \
  --volume $PWD:/cwd \
  --volume $PWD/.terraform:/cwd/.terraform \
  --volume $HOME/.aws:/root/.aws \
  --volume $HOME/.terraformrc:/root/.terraformrc \
  --volume $HOME/.terraform.d:/root/.terraform.d \
  --env AWS_ACCESS_KEY_ID \
  --env AWS_SECRET_ACCESS_KEY \
  --env AWS_SESSION_TOKEN \
  --env AWS_DEFAULT_REGION \
  ${TERRAFORM_IMAGE}:${TERRAFORM_HASH} "$@"
